version: '3.5'
services:
  mercury_express_api:
    container_name: mercury_express_api
    build: .
    image: mercury_express_api
    user: node
    working_dir: /home/node/app
    labels:
      traefik.backend: "mercury_express_api"
      traefik.docker.network: "host"
      traefik.frontend.rule: "Host:mercury-dev-api.chas.school"
    volumes:
      - ./:/home/node/app
    environment:
      - POSTGRES_HOST=database
    depends_on:
      - mercury_database
    env_file:
      - .env
  mercury_database:
    container_name: mercury_postgres_db
    image: postgres:9.6
    labels:
      traefik.backend: "mercury_express_api"
      traefik.docker.network: "host"
    volumes:
      - mercury_database:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  mercury_database:
