version: '3.5'

services:
  api:
    image: ludlun/mercury-api-dev:latest
    working_dir: /app
    command: node dist/server.js
    environment:
      - POSTGRES_HOST=database
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - traefik
    deploy:
      labels:
        traefik.port: '7770'
        traefik.backend: 'mercury_staging'
        traefik.docker.network: 'traefik'
        traefik.frontend.rule: 'Host:mercury-api-staging.chas.school'
  database:
    image: 'postgres:9.6'
    volumes:
      - 'database:/var/lib/postgresql/data'
    env_file:
      - .env
    networks:
      - traefik
    deploy:
      labels:
        traefik.docker.network: traefik
volumes:
  database:

networks:
  traefik:
    external: true
